Главная страница
htmlacademy-htmlcss/1821427-technomart-31 pull request #2
Opened 2021-05-26 20:14 UTC by ElenaAgeeva2505

2021-05-28 15:47 UTC, costigans requested changes
Нужно исправить ошибки валидатора
https://validator.w3.org/nu/?doc=https%3A%2F%2Fhtmlacademy-htmlcss.github.io%2F1821427-technomart-31%2F2%2F

2021-05-28 15:48 UTC, costigans commented
Старайся именовать класс и файлы понятными словами.
Так будет удобнее работать с проектами тебе в будущем и другим разработчикам на проекте. Идеи можно взять [отсюда](https://github.com/yoksel/common-words)

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +	  <h1>Техномарт</h1>
Это не h1

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +	    <p>Интернет-магазин  <br>строительных материалов  <br>и инструментов для ремонта</p>
Вот h1 — главный заголовок. Прочитав его станет понятно о чём это страница

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +    <section class="top-bar-container">
`section` тут лишний, слишком мало информации, чтобы выделять её как какой-то раздел.
Достаточно просто `div`

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +	  <a href="index.html" class="logo"><img src="img/logo.jpg" alt="Техномарт Логотип" width="220" height="50"></a>
Здесь (на главной странице) можешь удалить аттрибут `href`, есть хорошая рекомендация — на странице не должно быть ссылок на саму себя.
На главной убрать все `href` в тегах `a`, в том числе и в меню.

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +	  <input type="search" placeholder="Поиск:">
«Поиск:» это лейбл, а не плейсхролдер

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +		<li class="top-bar-item"><button type="button">Оформить заказ</button></li>
Может ли кнопка здесь быть ссылкой и вести на отдельную страницу оформления заказа?

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +		</ul>
Можно обойтись без ul — будет проще.

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +		 <li class="login-item"><button type="button">Регистрация</button></li>
Ссылки или кнопки?

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +	<div class="header-nav">
Зачем тебе лишняя «обёртка» над `nav`?

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +	</div>
По всему документу скачут отступы, а нужно их выровнять, загугли как это делается в твоём редакторе.
С аккуратным кодом будет проще работать и тебе, и мне :)

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +	<h2>Каталог товаров</h2>
Это не раздел каталога товаров, а некоторый его части — популярных товаров :)

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +	 </div>
Не нашёл элемента с «Все популярные товары»

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +		 <p>г. Санкт-Петербург, наб. Реки Карповки, 5 лит П +7 800 555-86-28</p>
Раздели на два тега — это два разных элемента

2021-05-31 23:13 UTC, costigans commented on catalog.html
> +		</ul>
Супер, верно разбила на списки. только удали лишние пробелы в ссылках

2021-05-31 23:20 UTC, costigans requested changes

2021-05-31 23:20 UTC, costigans commented on catalog.html
> +		 <li class="login-item"><button type="button">Регистрация</button></li>
На этой странице контент отличается от Главной

2021-05-31 23:20 UTC, costigans commented on index.html
> +	  <a href="#" class="logo"><img src="img/logo.jpg" alt="Техномарт Логотип" width="220" height="50"></a>
Здесь (на главной странице) можешь удалить аттрибут `href`, есть хорошая рекомендация — на странице не должно быть ссылок на саму себя.
На главной убрать все `href` в тегах `a`, в том числе и в меню.

2021-05-31 23:20 UTC, costigans commented on index.html
> +		<li class="menu-desktop-item"><a href="#"> <img src="" alt="Доставка"></a></li>
Изображения здесь несут главную или декоративную функцию сопровождая основной контент?
Представь если бы их здесь совсем не было, сильно бы это повлияло на смысл этих ссылок?

2021-05-31 23:20 UTC, costigans commented on index.html
> +		      <p>
Для чего тут `p`?

2021-05-31 23:20 UTC, costigans commented on index.html
> +			<p><button type="button">Заблудились? Напишите нам</button></p>
Зачем `p`?

2021-05-31 23:21 UTC, costigans commented
Отлично постаралась, я не нашёл ни одной грубой ошибки. Все теги подобраны очень грамотно. Ты молодец

2021-06-01 18:17 UTC, ElenaAgeeva2505 commented on index.html
> +		<li class="menu-desktop-item"><a href="#"> <img src="" alt="Доставка"></a></li>
Я не соображу, как оформить. Наверно, декоративную.

2021-06-03 10:27 UTC, costigans commented on catalog.html
> +	  <h2>Техномарт</h2>
Здесь вообще не нужен заголовок

2021-06-03 10:27 UTC, costigans commented on catalog.html
> +	     <button type="button">Равшан Джамшутович</button>
А точно это кнопка?

2021-06-03 10:27 UTC, costigans commented on index.html
> +	  <h2>Техномарт</h2>
Удали

2021-06-03 10:27 UTC, costigans commented on index.html
>  	  <div class="slider">
Давай разделим на два списка?
Один про ассортимент:
- Материалы
- Инструменты
- Техника

Другой про сервис:
- Скидка
- Доставка

2021-06-03 10:27 UTC, merged